### ISSUE TITLE
Creative Server instances sometimes not cleaned up

### ISSUE THREAD

**Issue by derekmiranda** [ff0000-tech/build-source-automator#2] opened 2019-07-02 22:07 UTC
Noticed this when working with Assembler so could possibly be an issue there

Seems that on any error w/ the `csManager.compile()` process, CS may not be stopped. Could be as simple as adding a `stopCreativeServer()` call in the `catch` [here](https://github.com/ff0000-tech/build-source-automator/blob/2a201e14dd7ab6978deaec5366d4dd1ba9d0bb3e/lib/cs-manager.js#L20) or putting it in a `finally()` call

**Comment by gmcdev** [comment] 2019-07-02 22:21
Thanks for noting this. I've definitely fought this issue quite a bit.

The problem is is that `stopCreativeServer()` currently assumes CS is running and sends an API request for it to shut itself down. However, critical errors can also happen during the CS launch phase, in which case, there is no API to receive the request. Error in an error.

That said, the spirit of your idea is right, except`stopCreativeServer()` needs to be a BSA process that kills the CS process. 

Unfortunately, tracking the process-id of the CS process is challenging, because it would need to be stored at the module level of cs-manager. That gets hairy with many CS processes running concurrently. What to do... 

In the meantime, BSA flags CS to timeout, so that if CS receives no API requests during timeout, it shuts itself down.

**Comment by derekmiranda** [comment] 2019-07-02 22:28
Ahh I see. I mainly noticed this when trying to update more than one Builder Template at a time which I was able to do pretty easily before. But just today, I've been running into the Creative Server Timeout error so have had to update them one at a time

**Comment by gmcdev** [comment] 2019-07-03 19:37
addressed in 2.2.3

**Closed by gmcdev** 2019-07-03 19:37 UTC
